Done project
3elt3er/curriculum-vitae pull request #3
Opened 2022-07-16 13:55 UTC by 3elt3er

2022-07-20 09:23 UTC, maximzadorkin requested changes
Название пр так не делают)) Как и писал тебе раньше - нужно осмысленно писать,  что за фичу ты добавляешь

2022-07-20 09:23 UTC, maximzadorkin commented on index.html
>      <head>
Название пр так не делают)) Как и писал тебе раньше - нужно осмысленно писать,  что за фичу ты добавляешь

2022-07-20 09:23 UTC, maximzadorkin commented on index.html
> +        <link rel="stylesheet" href="styles.css"/>
Неплохо бы было попробовать несколько css файлов + тег style + атрибут style

2022-07-20 09:23 UTC, maximzadorkin commented on index.html
> +                    <img src="Me.jpg" alt="Здесь должна быть фотка меня" class="PhotoMe"/>
alt следует писать осмысленно, даже если делаешь проект для себя. Мало ли придется этот код где-то юзануть

2022-07-20 09:23 UTC, maximzadorkin commented on index.html
>          <p><strong>Специализации:</strong></p>
раз уж перешел на css - делай все выделения с помощью css, а не тегами. Потому что разные браузеры по разному один и тот же тег могут разрисовать. Дело в том, что теги помимо семантики несут за собой набор дефолтных стилей. И от браузера стили тега могут изменяться

2022-07-20 09:23 UTC, maximzadorkin commented on index.html
>          <label for="text">Ваше сообщение:</label>
вообще думаю тут можно было бы просто в label textarea запихнуть, а не дивами обворачивать

2022-07-20 09:23 UTC, maximzadorkin commented on map.html
> +       <img src="Moscow Map.png" width="800" hspace="350" alt="Здесь должна быть фотка карты">
опять же про alt помним

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Slab&display=swap');
нужно копнуть глубже. Прочти https://habr.com/ru/company/htmlacademy/blog/552388/

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +    background: rgba(255, 165, 0, 0.25);
попробуй hex выставлять,  а не только rgba

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +    color: #000;
Вообще обычно всегда используют полный hex / rgba. Но тут конечно на усмотрение, все равно попробуй к полному hex прийти

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +.button:hover {
Добавь чтобы можно было клавишей таб навестись и border у кнопки становился зеленым

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +.button:hover {
Сейчас там синим цветом выделяется и не border, а outline. А ты убери outline и сделай именно бордером

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +@media (max-width: 1000px) {
неплохо. бы с паддингами на маленьких экранах пробежаться, а то больно

2022-07-20 09:23 UTC, maximzadorkin commented on index.html
>          <title>Adilgereev CV</title>
Посмотри вот это:
```
<meta name="viewport" content="width=device-width, initial-scale=1">
```
Необходимо для мобильных устройств, почитай

2022-07-20 09:23 UTC, maximzadorkin commented on styles.css
> +}
не нашел ни одного обращения по id и атрибуту. Добавь ради изучения

2022-07-20 09:29 UTC, maximzadorkin commented
social media tags не сделано

2022-07-20 09:34 UTC, maximzadorkin commented
изучи flex и юзани

2022-07-20 09:35 UTC, maximzadorkin commented
изучи grid и юзани

2022-08-07 22:22 UTC, 3elt3er commented on index.html
>          <title>Adilgereev CV</title>
Понял, это для оптимизации сайтов с адаптивным дизайном, чтобы красиво отображалось на мобильных устройствах, тк если этого не задать, будет взято дефолтное значение браузера, а на всех браузерах оно разное, поэтому может произойти shit.

2022-08-07 22:25 UTC, 3elt3er commented on index.html
> +        <link rel="stylesheet" href="styles.css"/>
Тег style нужен для того, чтобы не подключая файл css использовать его стили в файле html. Считается, что так делать не нужно, но может пригодиться, добавлять не буду, но знаю как он работает, тк не хочу совсем костыли делать...

2022-08-07 22:32 UTC, 3elt3er commented on index.html
> +        <link rel="stylesheet" href="styles.css"/>
Файл css добавил.

2022-08-08 00:29 UTC, 3elt3er reviewed
Всё исправил. Сейчас залью pr.

2022-08-08 00:29 UTC, 3elt3er commented on index.html
>          <p><strong>Специализации:</strong></p>
Понял, когда переделывал в css не увидел, что это не исправлено было.

2022-08-08 00:29 UTC, 3elt3er commented on index.html
>          <label for="text">Ваше сообщение:</label>
Не совсем понял как.

2022-08-08 00:29 UTC, 3elt3er commented on styles.css
> +.button:hover {
Сделано

2022-08-08 00:49 UTC, merged